name = "spirit-bar"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[assets.serving]
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "spirit-bar-db"
database_id = "e7e0f588-0bda-4bbd-a1c5-d4972e441f03"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "spirit-bar-photos"

[vars]
ENVIRONMENT = "development"
